### ISSUE TITLE
SocialNetworkAnalyticsBenchmark1 does not work

### ISSUE THREAD

**Issue by Informagier** [dbs-leipzig/gradoop-benchmarks#4]
The SNA-Benchmark1 does not work in its default configuration e.g. when no command line arguments are supplied.
When started from the terminal, the following output is produced: https://pastebin.com/2FAgZ9bR

**Comment by ChrizZz110** [comment]
Hi @Informagier, thanks for your issue.

The SNA-Benchmark1 has two ways to run - 1) with external data from the LDBC dataset and 2) with demo data. The second option is executable in a local environment only, because of the graph.print() functionality used does not work on a cluster environment. 

If you want to see an output, you can remove the two `.print()` calls in function `executeWithDemoData()` and output the graph in a `DotDataSink`. Then you can open the result with [GraphViz](https://www.graphviz.org/) or [Gephi](https://gephi.org/).

```
LogicalGraph inputGraph = loader.getLogicalGraphByVariable("db");
System.out.println("Input Graph");
//inputGraph.print();

LogicalGraph outputGraph = execute(inputGraph, 2);
System.out.println("Output Graph");
//outputGraph.print();

outputGraph.writeTo(new DOTDataSink("/home/christopher/tmp/dot.dot", true));
gradoopConf.getExecutionEnvironment().execute();
```
